- name: Add apt key
  apt_key:
    id: 0C49F3730359A14518585931BC711F9BA15703C6
    keyserver: keyserver.ubuntu.com
  tags: install

- name: Fetch the mongodb repo
  apt_repository:
    repo: deb [ arch=amd64,arm64 ] http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.4 multiverse
    state: present
  tags: install

- name: Install MongoDB
  apt:
    name: mongodb-org
    state: present
  tags: install

- name: Unabled service
  systemd:
    name: mongod
    enabled: yes
    state: started
  tags: install

# - name: Add APT key
#   apt_key:
#     id: "EA312927"
#     keyserver: keyserver.ubuntu.com
#   tags: install

# - name: Add APT repository
#   apt_repository:
#     repo: deb [ arch=amd64,arm64 ] http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
#     state: present
#   tags: install

# - name: Install mongodb package
#   apt:
#     name: mongodb-org
#     state: present
#   tags: install

# - name: Configure service supervisor
#   systemd:
#     name: mongod
#     enabled: yes
#     state: started
#   tags: install
