---
- name: Install MondoDB
  hosts: all
  become: true
  tasks:
    - name: Add apt key
      apt_key:
        id: 0C49F3730359A14518585931BC711F9BA15703C6
        keyserver: keyserver.ubuntu.com

    - name: Fetch the mongodb repo
      apt_repository:
        repo: deb [ arch=amd64,arm64 ] http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.4 multiverse
        state: present

    - name: Install MongoDB
      apt:
        name: mongodb-org
        state: present

    - name: Unabled service
      systemd:
        name: mongod
        enabled: yes
